import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;
// Using AWT containers and components
// Using AWT events and listener interfaces

public class GraphingData extends javax.swing.JFrame {

	/**
	 * Creates new form GraphingData
	 */
	public GraphingData() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField1.setText("Enter your java code here");

		jButton1.setText("Run Taint analysis");

		jTextField2.setText("Jimple appears here");

		jTextField3.setText("Tainted variables appear here");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField1)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTextField2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		262,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jTextField3,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		292,
																		Short.MAX_VALUE)))
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addGap(239, 239, 239)
								.addComponent(jButton1)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										150,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														97, Short.MAX_VALUE)
												.addComponent(jTextField3))
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String javaCode = jTextField1.getText();
		try {
			PrintWriter writer = new PrintWriter(
					"/Users/Rishi/Documents/Master_folder/Semester_7/Program_analysis/Assignments/Workspace/TaintVisualiser/src/Test.java");
			writer.println(javaCode);
			writer.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
		String arr[] = { "Test" };
		Taint.main(arr);
		String filepath = "/Users/Rishi/Documents/Master_folder/Semester_7/Program_analysis/Assignments/Workspace/context.txt";
		String keysFile = "/Users/Rishi/Documents/Master_folder/Semester_7/Program_analysis/Assignments/Workspace/keys.txt";
		String taintedFile = "/Users/Rishi/Documents/Master_folder/Semester_7/Program_analysis/Assignments/Workspace/taint.txt";
		String jimple = "";
		try {
			BufferedReader br = new BufferedReader(new FileReader(filepath));
			while (br.readLine() != null) {
				jimple = jimple + br.readLine() + "\n";
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
		jTextField2.setText(jimple);
		String taintedVars = "";
		try {
			BufferedReader br = new BufferedReader(new FileReader(taintedFile));
			while (br.readLine() != null) {
				taintedVars += br.readLine() + "\n";
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
		jTextField3.setText(taintedVars);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GraphingData.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GraphingData.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GraphingData.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GraphingData.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GraphingData().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration
}
